import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  button: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DCDCDC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  checkedButton: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#04549b',
  },

  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeContainer: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainer: {
    marginTop: 50,
    flexDirection: 'column',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gameTitleView: {
    flexDirection: 'row',
  },
  gameTitle: {
    fontSize: 20,
  },
  keyboard: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  keyboardRow: {
    flex: 1,
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 40,
  },
  keyItem: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  usedKey: {
    color: 'grey',
    fontSize: 20,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  letter: {
    color: 'black',
    fontSize: 20,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashInputStyle: {
    height: 40,
  },
  dashes: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'auto',
    justifyContent: 'center',
    flexWrap: 'wrap',
    margin: 40,
  },
  dashItemContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashItem: {
    width: 20,
    color: '#841584',
    fontSize: 20,
    borderBottomColor: 'black',
  },
  dashBlankItem: {
    width: 100,
    fontSize: 20,
  },
  hintContainer: {
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    padding: 10,
  },
  hintText: {
    fontSize: 18,
    fontWeight: '500',
  },
  scoreText: {
    fontSize: 13,
    textAlign: 'left',
    fontWeight: '500',
    justifyContent: 'flex-start',
    width: '100%',
    padding: 20,
  },
  pageCountText: {
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '500',
    justifyContent: 'flex-start',
    width: '100%',
    padding: 10,
  },
  guessSquare: {
    borderColor: '#d3d6da',
    borderWidth: 2,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 3,
  },
  puzzleTitle: {
    borderColor: '#d3d6da',
    borderWidth: 2,
    backgroundColor: '#D9E7FB',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 120,
    paddingTop: 10,
    paddingBottom: 10,
    paddingStart: 30,
    paddingEnd: 30,
  },
  gameTitleSquare: {
    borderColor: '#d3d6da',
    borderWidth: 2,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
  },
  startButtonContainer: {
    backgroundColor: '#FECBCA',
    borderColor: '#d3d6da',
    borderWidth: 2,
    height: 50,
    width: 240,
    alignItems: 'center',
    paddingStart: 30,
    paddingEnd: 30,
    marginTop: 50,
  },
  winText: {
    fontSize: 30,
    textAlign: 'center',
    fontWeight: '500',
    width: '100%',
    padding: 5,
  },
});

export default styles;
